name: ${project.name}
version: ${project.version}
description: ${project.description}
author: aumgn
website: ${project.url}

main: fr.aumgn.motd.plugin.RandomMotd

commands:
    motd:
        description: "Main motd command"
        usage: "/<command> reload | set [motd]"
        permission: "randommotd.command"
        
permissions:
    randommotd.command:
        default: op
